; ModuleID = 'globals.c'
source_filename = "globals.c"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

%struct.SGFTree_t = type { %struct.SGFNode_t*, %struct.SGFNode_t* }
%struct.SGFNode_t = type { %struct.SGFProperty_t*, %struct.SGFNode_t*, %struct.SGFNode_t*, %struct.SGFNode_t* }
%struct.SGFProperty_t = type { %struct.SGFProperty_t*, i16, i8* }
%struct.dragon_data2 = type { i32, [10 x i32], i32, i32, i32, float, i32, float, float, i32, %struct.eyevalue, i32, i32, i32, i32, i32, i32 }
%struct.eyevalue = type { i8, i8, i8, i8 }
%struct.Hash_data = type { [1 x i64] }
%struct.stats_data = type { i32, i32, i32, i32, i32, i32 }
%struct.worm_data = type { i32, i32, float, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, [10 x i32], [10 x i32], [10 x i32], [10 x i32], [10 x i32], [10 x i32], [10 x i32], [10 x i32] }
%struct.dragon_data = type { i32, i32, i32, i32, float, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32 }
%struct.half_eye_data = type { float, i8, i32, [4 x i32], i32, [4 x i32] }
%struct.eye_data = type { i32, i32, i32, i32, %struct.eyevalue, i32, i32, i8, i8, i8, i8, i8 }
%struct.surround_data = type { i32, [400 x i8] }

@board_size = dso_local global i32 19, align 4
@thrashing_dragon = dso_local global i32 0, align 4
@hashflags = dso_local global i32 7969, align 4
@quiet = dso_local global i32 0, align 4
@showstatistics = dso_local global i32 0, align 4
@allpats = dso_local global i32 0, align 4
@printworms = dso_local global i32 0, align 4
@printmoyo = dso_local global i32 0, align 4
@printboard = dso_local global i32 0, align 4
@count_variations = dso_local global i32 0, align 4
@sgf_dump = dso_local global i32 0, align 4
@sgf_dumptree = dso_local global %struct.SGFTree_t* null, align 8
@random_seed = dso_local global i32 0, align 4
@loading = dso_local global i32 0, align 4
@fusekidb = dso_local global i32 1, align 4
@disable_fuseki = dso_local global i32 0, align 4
@josekidb = dso_local global i32 1, align 4
@showtime = dso_local global i32 0, align 4
@showscore = dso_local global i32 0, align 4
@score = dso_local global float 0.000000e+00, align 4
@lower_bound = dso_local global float 0.000000e+00, align 4
@upper_bound = dso_local global float 0.000000e+00, align 4
@level = dso_local global i32 10, align 4
@urgent = dso_local global i32 0, align 4
@debug = dso_local global i32 0, align 4
@verbose = dso_local global i32 0, align 4
@outfilename = dso_local global [128 x i8] zeroinitializer, align 16
@output_flags = dso_local global i32 0, align 4
@disable_threat_computation = dso_local global i32 0, align 4
@disable_endgame_patterns = dso_local global i32 0, align 4
@doing_scoring = dso_local global i32 0, align 4
@chinese_rules = dso_local global i32 0, align 4
@experimental_semeai = dso_local global i32 1, align 4
@semeai_variations = dso_local global i32 250, align 4
@experimental_connections = dso_local global i32 1, align 4
@owl_threats = dso_local global i32 0, align 4
@experimental_owl_ext = dso_local global i32 0, align 4
@allow_suicide = dso_local global i32 0, align 4
@capture_all_dead = dso_local global i32 0, align 4
@play_out_aftermath = dso_local global i32 0, align 4
@play_mirror_go = dso_local global i32 0, align 4
@mirror_stones_limit = dso_local global i32 -1, align 4
@gtp_version = dso_local global i32 2, align 4
@dragon2 = dso_local global %struct.dragon_data2* null, align 8
@board = dso_local global [421 x i8] zeroinitializer, align 16
@board_ko_pos = dso_local global i32 0, align 4
@white_captured = dso_local global i32 0, align 4
@black_captured = dso_local global i32 0, align 4
@initial_board = dso_local global [421 x i8] zeroinitializer, align 16
@initial_board_ko_pos = dso_local global i32 0, align 4
@initial_white_captured = dso_local global i32 0, align 4
@initial_black_captured = dso_local global i32 0, align 4
@move_history_color = dso_local global [500 x i32] zeroinitializer, align 16
@move_history_pos = dso_local global [500 x i32] zeroinitializer, align 16
@move_history_pointer = dso_local global i32 0, align 4
@komi = dso_local global float 0.000000e+00, align 4
@movenum = dso_local global i32 0, align 4
@shadow = dso_local global [400 x i8] zeroinitializer, align 16
@hashdata = dso_local global %struct.Hash_data zeroinitializer, align 8
@potential_moves = dso_local global [19 x [19 x float]] zeroinitializer, align 16
@stackp = dso_local global i32 0, align 4
@position_number = dso_local global i32 0, align 4
@depth = dso_local global i32 0, align 4
@backfill_depth = dso_local global i32 0, align 4
@backfill2_depth = dso_local global i32 0, align 4
@superstring_depth = dso_local global i32 0, align 4
@fourlib_depth = dso_local global i32 0, align 4
@ko_depth = dso_local global i32 0, align 4
@branch_depth = dso_local global i32 0, align 4
@aa_depth = dso_local global i32 0, align 4
@owl_distrust_depth = dso_local global i32 0, align 4
@owl_branch_depth = dso_local global i32 0, align 4
@owl_reading_depth = dso_local global i32 0, align 4
@owl_node_limit = dso_local global i32 0, align 4
@mandated_depth = dso_local global i32 0, align 4
@mandated_backfill_depth = dso_local global i32 0, align 4
@mandated_backfill2_depth = dso_local global i32 0, align 4
@mandated_superstring_depth = dso_local global i32 0, align 4
@mandated_fourlib_depth = dso_local global i32 0, align 4
@mandated_ko_depth = dso_local global i32 0, align 4
@mandated_branch_depth = dso_local global i32 0, align 4
@mandated_aa_depth = dso_local global i32 0, align 4
@mandated_owl_distrust_depth = dso_local global i32 0, align 4
@mandated_owl_branch_depth = dso_local global i32 0, align 4
@mandated_owl_reading_depth = dso_local global i32 0, align 4
@mandated_owl_node_limit = dso_local global i32 0, align 4
@best_move_values = dso_local global [10 x float] zeroinitializer, align 16
@best_moves = dso_local global [10 x i32] zeroinitializer, align 16
@close_worms = dso_local global [400 x [4 x i32]] zeroinitializer, align 16
@number_close_worms = dso_local global [400 x i32] zeroinitializer, align 16
@close_black_worms = dso_local global [400 x [4 x i32]] zeroinitializer, align 16
@number_close_black_worms = dso_local global [400 x i32] zeroinitializer, align 16
@close_white_worms = dso_local global [400 x [4 x i32]] zeroinitializer, align 16
@number_close_white_worms = dso_local global [400 x i32] zeroinitializer, align 16
@false_eye_territory = dso_local global [400 x i32] zeroinitializer, align 16
@stats = dso_local global %struct.stats_data zeroinitializer, align 4
@worm = dso_local global [400 x %struct.worm_data] zeroinitializer, align 16
@dragon = dso_local global [400 x %struct.dragon_data] zeroinitializer, align 16
@number_of_dragons = dso_local global i32 0, align 4
@half_eye = dso_local global [400 x %struct.half_eye_data] zeroinitializer, align 16
@owl_half_eye = dso_local global [400 x %struct.half_eye_data] zeroinitializer, align 16
@black_eye = dso_local global [400 x %struct.eye_data] zeroinitializer, align 16
@white_eye = dso_local global [400 x %struct.eye_data] zeroinitializer, align 16
@owl_black_eye = dso_local global [400 x %struct.eye_data] zeroinitializer, align 16
@owl_white_eye = dso_local global [400 x %struct.eye_data] zeroinitializer, align 16
@surroundings = dso_local global [10 x %struct.surround_data] zeroinitializer, align 16
@surround_pointer = dso_local global i32 0, align 4

!llvm.module.flags = !{!0, !1, !2}
!llvm.ident = !{!3}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 7, !"uwtable", i32 1}
!2 = !{i32 7, !"frame-pointer", i32 2}
!3 = !{!"clang version 13.0.0"}
